


echo "calculate the band-structure of MgO on HSE level using wannierization"

#NP=1 #number of processors
rm -f kpoints.dat

k="5"
q="2"
lat="6.22"
hlat=$(awk '{print ($1*0.5)}' <<< "${lat}")

<

a1="Co"
a2="Co"
a3="Sc"
a4="Sb"
nbands="70"

cat >scf.in <<EOF
&control
 calculation='scf',
 prefix='dat',
 pseudo_dir= './pseudos',
 outdir = './scratch',
 wf_collect = .true.,
 max_seconds = 4500 
 !max_seconds='3600', 
/
&system
 ibrav=2,
 A=$lat
 !celldm(1) = 8.0420
 nat=4,
 ntyp=4,
 noncolin= .true. 
 lspinorb = .true.
 nosym= .true.
 noinv = .true.
 no_t_rev = .true.
 starting_magnetization(1)= 0.15
 starting_magnetization(2)= 0.15
 starting_magnetization(3)= -0.05
 starting_magnetization(4)= 0,	!starting magnetization
 report = 1,
 
 ecutwfc = 100,
 ecutfock = 200,
 ecutrho = 400,
 nbnd = $nbands
 input_dft='HSE'
 nqx1=$q, nqx2=$q, nqx3=$q !this is NOT converged but fast
 occupations='smearing', 		!used with systems with metals. Doesn't fix occupations. 
 smearing='gaussian', 			!type of smearing... see http://theossrv1.epfl.ch/Main/ElectronicTemperature
 degauss=0.01 			!value of gaussian spreading for brillouin zone integration
  
/
&electrons
 conv_thr=1.d-6,
 adaptive_thr = .true.
 mixing_beta = 0.5
/
ATOMIC_SPECIES
 ${a1}1 58.933 ${a1}.UPF
 ${a2}2 58.933 ${a2}.UPF
 ${a3} 44.956 ${a3}.UPF
 ${a4} 121.76 ${a4}.UPF
ATOMIC_POSITIONS crystal
 ${a3} 0.00000 0.00000 0.0000
 ${a1}1 0.25000 0.25000 0.2500
 ${a4} 0.50000 0.50000 0.5000
 ${a2}2 0.75000 0.75000 0.7500
K_POINTS {automatic}
 $k $k $k 0 0 0
EOF

echo "Printed SCF file"

module load qe/6.6

ibrun pw.x -input scf.in

cat >opengrid.in <<EOF
&inputpp 
   outdir = './scratch'
   prefix = 'dat'
/
EOF

ibrun $qePathEdited/open_grid.x -input opengrid.in >opengrid.out





#this grabs the k-point list generated by open_grid.x
awk '/wannier90/{flag=1;next}/OPEN_GRID    :/{flag=0}flag' opengrid.out >kpoints.dat

cat > heusler.win <<EOF
num_wann        = $nbands
num_bands       = $nbands
dis_num_iter    = 400
num_iter        = 100
guiding_centres =.true.

!dis_win_min       = -8.0d0
!dis_win_max       = 70.0d0
!dis_froz_min      = -8.0d0


dis_win_min = 8.1
dis_win_max = 20.15
dis_froz_min = -20
dis_froz_max = 50.15
begin atoms_frac
 ${a3} 0.00000 0.00000 0.0000
 ${a1} 0.25000 0.25000 0.2500
 ${a4} 0.50000 0.50000 0.5000
 ${a2} 0.75000 0.75000 0.7500
end atoms_frac

spinors = true
begin projections
random
${a1}:d
${a3}:d
${a4}:p
end projections


begin unit_cell_cart
angstrom
-$hlat 0.000 $hlat
0.000 $hlat $hlat
-$hlat $hlat 0.000
end_unit_cell_cart

kpath = true
kpath_task = bands
kpath_bands_colour = spin
!kpath_num_points=500

begin kpoint_path
G  0.000000 0.00000 0.00000  X  0.500000 0.00000 0.50000
X  0.500000 0.00000 0.50000  W  0.500000 0.25000 0.75000
W  0.500000 0.25000 0.75000  K  0.375000 0.37500 0.75000
K  0.375000 0.37500 0.75000  G  0.000000 0.00000 0.00000
end kpoint_path

mp_grid : $k $k $k

begin kpoints
$(cat kpoints.dat)
end kpoints
EOF

cat >pw2wannier90.in <<EOF
&inputpp 
   outdir = './scratch'
   prefix = 'dat'
   seedname = 'heusler'
   write_spn = .true.   
   write_mmn = .true.
   write_amn = .true.
   !write_unk = .true.
/
EOF

$qePathEdited/wannier90.x -pp heusler
ibrun $qePathEdited/pw2wannier90.x <pw2wannier90.in
$qePathEdited/wannier90.x heusler
bash plot.sh heusler_band.dat
